[tool.poetry]
name = "poet-api"
version = "4.1.1"
description = "Requests for all"
authors = ["raratiru"]
license = "BSD-3-Clause"
readme = "README.md"
packages = [{include = "api"}]

[tool.poetry.dependencies]
python = "^3.11"
pyrate-limiter = "^4"
filelock = "^3"


[tool.poetry.group.dev.dependencies]
mypy = "*"
bandit = "*"
flake8 = "*"
pytest = "*"
pytest-mock = "*"
pytest-cov = "*"
pytest-factoryboy = "*"
ipykernel = "*"
pytest-xdist = "*"
django-devapp = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["*/settings/*"]
include = ["api/*"]

[tool.pytest.ini_options]
pythonpath = [
  ".", "api"
]
console_output_style = "count"
addopts = """
  --cov --cov-branch --cov-report term-missing:skip-covered --log-cli-level=info
  --pdb -s -vvv
  """
