from collections.abc import Coroutine, Mapping
from typing import Any, Protocol


class SyncHttpResponse(Protocol):
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    @property
    def text(self) -> str: ...
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...


class AsyncHttpResponse(Protocol):
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    @property
    def text(self) -> Coroutine[Any, Any, str]: ...
    def json(self) -> Coroutine[Any, Any, Any]: ...
    def raise_for_status(self) -> None: ...
